"""criacao inicial das tabelas

Revision ID: 7288f83d2004
Revises: 
Create Date: 2026-01-25 12:10:16.104451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7288f83d2004'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('CLIENTE', 'BARBEIRO', 'ADMIN', name='tipousuario'), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('senha_hash', sa.String(length=255), nullable=False),
    sa.Column('data_cadastro', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email')
    )
    op.create_table('barbeiro',
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('especialidade', sa.String(length=100), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('comissao', sa.DECIMAL(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['id_barbeiro'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_barbeiro')
    )
    op.create_table('cliente',
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('preferencias', sa.Text(), nullable=True),
    sa.Column('data_ultima_visita', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_cliente')
    )
    op.create_table('agendamento',
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDENTE', 'CONFIRMADO', 'RECUSADO', 'CANCELADO', 'CONCLUIDO', 'NAO_COMPARECEU', name='statusagendamento'), nullable=True),
    sa.Column('tempo_total_estimado', sa.Integer(), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('data_ultima_atualizacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_barbeiro'], ['barbeiro.id_barbeiro'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_agendamento')
    )
    op.create_table('disponibilidade',
    sa.Column('id_disponibilidade', sa.Integer(), nullable=False),
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('data_hora_inicio', sa.DateTime(), nullable=False),
    sa.Column('data_hora_fim', sa.DateTime(), nullable=False),
    sa.Column('disponivel', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_barbeiro'], ['barbeiro.id_barbeiro'], ),
    sa.PrimaryKeyConstraint('id_disponibilidade')
    )
    op.create_table('disponibilidade_barbeiro',
    sa.Column('id_disponibilidade', sa.Integer(), nullable=False),
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora_inicio', sa.Time(), nullable=False),
    sa.Column('hora_fim', sa.Time(), nullable=False),
    sa.Column('tipo', sa.Enum('DISPONIVEL', 'FOLGA', 'FERIAS', 'MANUTENCAO', name='tipodisponibilidade'), nullable=True),
    sa.Column('recorrente', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_barbeiro'], ['barbeiro.id_barbeiro'], ),
    sa.PrimaryKeyConstraint('id_disponibilidade')
    )
    op.create_table('especialidade',
    sa.Column('id_especialidade', sa.Integer(), nullable=False),
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_barbeiro'], ['barbeiro.id_barbeiro'], ),
    sa.PrimaryKeyConstraint('id_especialidade')
    )
    op.create_table('preferencia',
    sa.Column('id_preferencia', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_preferencia')
    )
    op.create_table('servico',
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('duracao_estimada', sa.Integer(), nullable=False),
    sa.Column('preco', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('id_barbeiro_criador', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['id_barbeiro_criador'], ['barbeiro.id_barbeiro'], ),
    sa.PrimaryKeyConstraint('id_servico')
    )
    op.create_table('agendamento_servico',
    sa.Column('id_agendamento_servico', sa.Integer(), nullable=False),
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('id_servico', sa.Integer(), nullable=False),
    sa.Column('preco_na_epoca', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_agendamento'], ['agendamento.id_agendamento'], ),
    sa.ForeignKeyConstraint(['id_servico'], ['servico.id_servico'], ),
    sa.PrimaryKeyConstraint('id_agendamento_servico')
    )
    op.create_table('historico_servico',
    sa.Column('id_historico', sa.Integer(), nullable=False),
    sa.Column('id_agendamento', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('data_servico', sa.DateTime(), nullable=False),
    sa.Column('servicos_realizados', sa.Text(), nullable=False),
    sa.Column('valor_total', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_agendamento'], ['agendamento.id_agendamento'], ),
    sa.ForeignKeyConstraint(['id_barbeiro'], ['barbeiro.id_barbeiro'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_historico')
    )
    op.create_table('notificacao',
    sa.Column('id_notificacao', sa.Integer(), nullable=False),
    sa.Column('id_agendamento', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('CONFIRMACAO', 'CANCELAMENTO', 'REAGENDAMENTO', 'LEMBRETE', name='tiponotificacao'), nullable=True),
    sa.Column('canal', sa.Enum('EMAIL', 'SMS', 'PUSH', name='canalnotificacao'), nullable=True),
    sa.Column('destinatario', sa.String(length=255), nullable=True),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('status_envio', sa.Enum('PENDENTE', 'ENVIADO', 'FALHA', name='statusenvio'), nullable=True),
    sa.Column('tentativas', sa.Integer(), nullable=True),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_agendamento'], ['agendamento.id_agendamento'], ),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id_cliente'], ),
    sa.PrimaryKeyConstraint('id_notificacao')
    )
    op.create_table('registro_financeiro',
    sa.Column('id_registro', sa.Integer(), nullable=False),
    sa.Column('id_barbeiro', sa.Integer(), nullable=False),
    sa.Column('id_agendamento', sa.Integer(), nullable=True),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('valor', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('tipo', sa.Enum('SERVICO', 'COMISSAO', name='tiporegistrofinanceiro'), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_agendamento'], ['agendamento.id_agendamento'], ),
    sa.ForeignKeyConstraint(['id_barbeiro'], ['barbeiro.id_barbeiro'], ),
    sa.PrimaryKeyConstraint('id_registro')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registro_financeiro')
    op.drop_table('notificacao')
    op.drop_table('historico_servico')
    op.drop_table('agendamento_servico')
    op.drop_table('servico')
    op.drop_table('preferencia')
    op.drop_table('especialidade')
    op.drop_table('disponibilidade_barbeiro')
    op.drop_table('disponibilidade')
    op.drop_table('agendamento')
    op.drop_table('cliente')
    op.drop_table('barbeiro')
    op.drop_table('usuario')
    # ### end Alembic commands ###
